BLEU_FOLDER=bleu_folder

PRED_DIR=$BLEU_FOLDER/predictions
PRED_OUTPUT_NORMAL=predictions-normal.txt
PRED_OUTPUT_REPLACE=predictions-replace-unk.txt
PRED_OUTPUT_BEAM5=predictions-beam5.txt
PRED_OUTPUT_BEAM10=predictions-beam10.txt
PRED_OUTPUT_BEAM10_REPLACE=predictions-beam10-replace-unk.txt
PRED_OUTPUT_BEAM10PEN1=predictions-beam10-pen1.txt
PRED_OUTPUT_BEAM10PEN1_REPLACE=predictions-beam10-pen1-replace-unk.txt

### Create Target ###
TARGET_FOLDER=$BLEU_FOLDER/target
TEST_TARGETS=$TARGET_FOLDER/test.3000.msg
mkdir -p $TARGET_FOLDER


DATASET_FOLDER=# Path to datasets folder
GITIGNORE_TARGET=$DATASET_FOLDER/gitignore/test.95.msg
GITREPO_TARGET=$DATASET_FOLDER/gitrepo/test.383.msg
GRADLE_TARGET=$DATASET_FOLDER/gradle/test.175.msg
JAVA_TARGET=$DATASET_FOLDER/java/test.436.msg
MD_TARGET=$DATASET_FOLDER/md/test.139.msg
OTHERS_V2_TARGET=$DATASET_FOLDER/others_v2/test.1119.msg
OTHERS_V1_TARGET=$DATASET_FOLDER/others_v1/test.1524.msg
PROPERTIES_TARGET=$DATASET_FOLDER/properties/test.106.msg
TXT_TARGET=$DATASET_FOLDER/txt/test.93.msg
XML_TARGET=$DATASET_FOLDER/xml/test.247.msg
YML_TARGET=$DATASET_FOLDER/yml/test.111.msg


# v2
#cat $GITIGNORE_TARGET $GITREPO_TARGET $GRADLE_TARGET $JAVA_TARGET $MD_TARGET $OTHERS_V2_TARGET $PROPERTIES_TARGET $TXT_TARGET $XML_TARGET $YML_TARGET > $TEST_TARGETS
# v1
cat $GRADLE_TARGET $JAVA_TARGET $MD_TARGET $OTHERS_V1_TARGET $XML_TARGET > $TEST_TARGETS

### Concat predictions
GITIGNORE_FOLDER=$BLEU_FOLDER/gitignore
GITREPO_FOLDER=$BLEU_FOLDER/gitrepo
GRADLE_FOLDER=$BLEU_FOLDER/gradle
JAVA_FOLDER=$BLEU_FOLDER/java
MD_FOLDER=$BLEU_FOLDER/md
OTHERS_V2_FOLDER=$BLEU_FOLDER/others_v2
OTHERS_V1_FOLDER=$BLEU_FOLDER/others_v1
PROPERTIES_FOLDER=$BLEU_FOLDER/properties
TXT_FOLDER=$BLEU_FOLDER/txt
XML_FOLDER=$BLEU_FOLDER/xml
YML_FOLDER=$BLEU_FOLDER/yml

mkdir -p $BLEU_FOLDER
mkdir -p $GITIGNORE_FOLDER
mkdir -p $GITREPO_FOLDER
mkdir -p $GRADLE_FOLDER
mkdir -p $JAVA_FOLDER
mkdir -p $MD_FOLDER
mkdir -p $OTHERS_FOLDER
mkdir -p $OTHERS_V1_FOLDER
mkdir -p $PROPERTIES_FOLDER
mkdir -p $TXT_FOLDER
mkdir -p $XML_FOLDER
mkdir -p $YML_FOLDER

mkdir -p $PRED_DIR

GITIGNORE_PREDICTIONS=# Path to gitignore predictions
GITREPO_PREDICTIONS=# Path to gitignore predictions
GRADLE_PREDICTIONS=# Path to gitignore predictions 
JAVA_PREDICTIONS=# Path to java predictions
MD_PREDICTIONS=# Path to md predictions
OTHERS_V2_PREDICTIONS=# Path to others v2 predictions
OTHERS_V1_PREDICTIONS=# Path to others v1 predictions
PROPERTIES_PREDICTIONS=# Path to properties predictions
TXT_PREDICTIONS=# Path to txt predictions
XML_PREDICTIONS=# Path to xml predictions
YML_PREDICTIONS=# Path to yml predictions

cp $GITIGNORE_PREDICTIONS/* $GITIGNORE_FOLDER
cp $GITREPO_PREDICTIONS/* $GITREPO_FOLDER
cp $GRADLE_PREDICTIONS/* $GRADLE_FOLDER
cp $JAVA_PREDICTIONS/* $JAVA_FOLDER
cp $MD_PREDICTIONS/* $MD_FOLDER
cp $OTHERS_V2_PREDICTIONS/* $OTHERS_V2_FOLDER
cp $OTHERS_V1_PREDICTIONS/* $OTHERS_V1_FOLDER
cp $PROPERTIES_PREDICTIONS/* $PROPERTIES_FOLDER
cp $TXT_PREDICTIONS/* $TXT_FOLDER
cp $XML_PREDICTIONS/* $XML_FOLDER
cp $YML_PREDICTIONS/* $YML_FOLDER


for file in $PRED_OUTPUT_NORMAL $PRED_OUTPUT_REPLACE $PRED_OUTPUT_BEAM5 $PRED_OUTPUT_BEAM10 $PRED_OUTPUT_BEAM10_REPLACE $PRED_OUTPUT_BEAM10PEN1 $PRED_OUTPUT_BEAM10PEN1_REPLACE
do
    # v2
    #cat $GITIGNORE_FOLDER/$file $GITREPO_FOLDER/$file $GRADLE_FOLDER/$file $JAVA_FOLDER/$file $MD_FOLDER/$file $OTHERS_V2_FOLDER/$file $PROPERTIES_PREDICTIONS/$file $TXT_PREDICTIONS/$file $XML_FOLDER/$file $YML_FOLDER/$file > $PRED_DIR/$file
    # v1
    cat $GRADLE_FOLDER/$file $JAVA_FOLDER/$file $MD_FOLDER/$file $OTHERS_V1_PREDICTIONS/$file $XML_FOLDER/$file > $PRED_DIR/$file
done


MULTI_BLEU_PERL_PATH=# Path to multi-bleu.perl script in seq2seq  Ex: seq2seq/bin/tools/multi-bleu.perl


echo "predictions-normal.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_NORMAL}

echo "predictions-replace-unk.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_REPLACE}

echo "predictions-beam5.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_BEAM5}

echo "predictions-beam10.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_BEAM10}

echo "predictions-beam10-replace-unk.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_BEAM10_REPLACE}

echo "predictions-beam10-pen1.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_BEAM10PEN1}

echo "predictions-beam10-pen1-replace-unk.txt"
$MULTI_BLEU_PERL_PATH ${TEST_TARGETS} < ${PRED_DIR}/${PRED_OUTPUT_BEAM10PEN1_REPLACE}


### Clean up ###
rm -rf $BLEU_FOLDER
